# $FreeBSD$

MASTERDIR=	${.CURDIR}/../DevRay-pkg-zabbix-proxy

PORTNAME=	DevRay-pkg-zabbix-proxy5

CONFLICTS=	DevRay-pkg-zabbix-proxy \
		DevRay-pkg-zabbix-proxy4 \
		DevRay-pkg-zabbix-proxy44 \
		DevRay-pkg-zabbix-proxy54 \
		DevRay-pkg-zabbix-proxy6 \
		DevRay-pkg-zabbix-proxy62

RUN_DEPENDS=	zabbix_proxy:net-mgmt/zabbix5-proxy

ZABBIXINTERNALNAME=	zabbix-proxy5
ZABBIXTITLE=	Zabbix Proxy 5.0
ZABBIXVERSION=	50

.include "${MASTERDIR}/Makefile"
