# $FreeBSD

MASTERDIR=	${.CURDIR}/../DevRay-pkg-zabbix-agent

PORTNAME=	DevRay-pkg-zabbix-agent5

CONFLICTS=	DevRay-pkg-zabbix-agent \
		DevRay-pkg-zabbix-agent4 \
		DevRay-pkg-zabbix-agent44 \
		DevRay-pkg-zabbix-agent54 \
		DevRay-pkg-zabbix-agent6 \
		DevRay-pkg-zabbix-agent62 \
		DevRay-pkg-zabbix-agent64

RUN_DEPENDS=	zabbix_agentd:net-mgmt/zabbix5-agent

ZABBIXINTERNALNAME=	zabbix-agent5
ZABBIXTITLE=	Zabbix Agent 5.0
ZABBIXVERSION=	50

.include "${MASTERDIR}/Makefile"
